### ISSUE TITLE
Passing params to firestore-pdf-generator

### ISSUE THREAD

**Issue by dasmeet** [pdfplum/pdfplum#10]
Hi!

Is it possible to pass parameters (same as in GET request for http-pdf-generator) to firestore pdf generator?

I have tried adding parameters to the firestore document, but it doesn't appear to be working.

**Comment by dasmeet** [comment]
Great... and thank you for this super useful extension :)

**Comment by sassanh** [comment]
Please check it here:
https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.13.1-rc.0

**Comment by dasmeet** [comment]
Works perfectly. Trigger onWrite instead of onCreate is also very useful.

Thank You!
