### ISSUE TITLE
Can't download generated PDF. "Check internet connection" error

### ISSUE THREAD

**Issue by prSamir** [pdfplum/pdfplum#12]
After generating a PDF and opening it in another tab when trying to download it through Chrome, Mozilla or Edge getting the "Check internet connection" error, all works fine in Safari and on Mobile. In Chrome if you go to Setting ➝ Privacy and Security ➝ Site Settings ➝ Content ➝ PDF Documents and change "Open PDFs in Chrome" to "Download PDFs" PDF is downloaded normally but without the preview window. Has anyone encountered such a problem? What was the issue?
Here is the piece of code I use to generate the PDF and open it in a new tab. "pdf" variable here is the bytes array returned by the extension:

	var arrBuffer = base64ToArrayBuffer(pdf)
	var newBlob = new Blob([arrBuffer], { type: 'application/pdf' })

	var data = window.URL.createObjectURL(newBlob)

	var link = document.createElement('a')
	document.body.appendChild(link)
	link.href = data
	link.target = '_blank'

	link.click()
	window.URL.revokeObjectURL(data)
	link.remove()

**Comment by sassanh** [comment]
I guess you are using http-pdf-generator, if your code snippet above works in Safari or when you set a setting in Chrome, it means the data generated by extension is correct and the extension has done its job successfully. The reason it doesn't work on some browsers has nothing to do with this extension.

BTW, did you already try these:
- https://stackoverflow.com/questions/53066089/how-to-open-pdf-blob-using-browsers-pdf-viewer-rather-than-downloading
- https://stackoverflow.com/questions/52878170/rendering-pdf-blob-on-chrome

**Comment by sassanh** [comment]
I close this as my understanding is this issue is not relevant to this extension.
I'm willing to reopen it if you provide a reasoning for the opposite.
