### ISSUE TITLE
Dynamic output Firebase storage bucket (feature request)

### ISSUE THREAD

**Issue by webthurwa** [pdfplum/pdfplum#18]
This is not an issue but a feature request. 

Is it possible to have a dynamic output storage bucket? Here I'm looking at cases where I have a multi-tenant application where I would like different clients to have their PDFs stored in different buckets.

**Comment by sassanh** [comment]
Thanks for suggesting this!
I implemented it in version 0.15.0, these are the rc links, kindly check if they are satisfying your requirements and inform me if it's good to be published.

- https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.15.0-rc.0
- https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/http-pdf-generator@0.15.0-rc.0

**Comment by sassanh** [comment]
@webthurwa Did you get a chance to test it?

**Comment by webthurwa** [comment]
> @webthurwa Did you get a chance to test it?

Adding a path to the storage bucket does not work e.g. `xxx.appspot.com/client/pdfs.` 
It only works with the original bucket e.g. `xxxx.appspot.com`

**Comment by sassanh** [comment]
Thanks for testing it! I will publish it now, it usually takes ~2 days to be reviewed by Firebase team.

> The parameter is actually `outputStoragePrefix`

I edited my post.
