### ISSUE TITLE
Having issues with extension parameters

### ISSUE THREAD

**Issue by lazmeister** [pdfplum/pdfplum#22]
We tried a few things and using the invoice example from here https://github.com/pdfplum/pdfplum/tree/main/template-samples/invoices but the extension does not run for us.

Does the template path have to be absolute? We have:

Template path
*******.appspot.com/Reports/template/index.zip

Output Firebase Storage prefix (Optional)
Reports

Output Firebase Storage bucket name
********.appspot.com

Firestore collection, its document creation events should be listened to
Reports

We have a collection called Reports in the main project, we create documents to the same json spec as the example invoice. We also have a Reports storage folder within the storage bucket. Did we get anything wrong in the config? Thank you

**Comment by sassanh** [comment]
@lazmeister  Thanks for taking the time to report this issue. I don't see an obvious issue with your configuration. I'm willing to work with you to find the issue but I need more information.

Please follow these steps:
1. Go to Firebase Console and go to extensions and select the installed instance of the pdfplum extension by clicking on the "Manage" button on its entry: 

  <img width="133" alt="image" src="https://github.com/pdfplum/pdfplum/assets/1270688/3d820ed5-7421-4ffe-8632-5c03154ef0f7">

2. Select "APIs and resources" on the left:

  <img width="326" alt="image" src="https://github.com/pdfplum/pdfplum/assets/1270688/9064ef9d-b3f0-4a0d-be88-8f8080a0bcef">

3. Click on the "View logs" hyperlink:

  <img width="617" alt="image" src="https://github.com/pdfplum/pdfplum/assets/1270688/2bd3e459-041c-4057-ac17-dd8caeefa378">

It should open the function logs in the Google Cloud console. Now please create a document in the `Reports` Firestore collection of the same project in which you have installed the extension. It should result in some logs being generated, probably including an error. Remove any important information from the logs and send them here.

**Comment by lazmeister** [comment]
Thanks for the response, so I switched it all to your demo data examples for the template and the json and now I'm getting the PDFs generating but they are not seeing the data from the file:
<img width="683" alt="image" src="https://github.com/pdfplum/pdfplum/assets/3281599/5751f946-454c-4d9c-9f8f-3db35c08ccfc">

Here is the data file in the collection that is uploaded (json) to be picked up by the extension<img width="725" alt="image" src="https://github.com/pdfplum/pdfplum/assets/3281599/7ac3fc17-0e32-46cd-8a74-bd9e4c35d9a2">

**Comment by lazmeister** [comment]
Here are the logs from the last run
<img width="802" alt="image" src="https://github.com/pdfplum/pdfplum/assets/3281599/27b70035-4a17-4603-9f8e-93b476f0655f">

**Comment by lazmeister** [comment]
![image](https://github.com/pdfplum/pdfplum/assets/3281599/8b553d8a-796b-4055-93e0-5cda0272d1d9)

**Comment by lazmeister** [comment]
is the json the wrong format maybe? 
<img width="298" alt="image" src="https://github.com/pdfplum/pdfplum/assets/3281599/4075a1aa-b610-490c-a782-f07900d385fc">

**Comment by sassanh** [comment]
> is the json the wrong format maybe?

Yes, the structure is not correct. `data` is for the http extension, you are using the firestore extension. The data for the firestore extension should be in the root of the document, other options, like `chromiumPdfOptions` should be under `_pdfplum_config`. I guess you are following the wrong `POSTINSTALL.md`, [this](https://github.com/pdfplum/pdfplum/blob/main/firestore-pdf-generator/POSTINSTALL.md) is the one you should follow for the firestore extension.

**Comment by lazmeister** [comment]
@sassanh You are the man! Thank you sir! 
<img width="646" alt="image" src="https://github.com/pdfplum/pdfplum/assets/3281599/4b810127-44d4-485c-bc30-910be4ec7138">
