### ISSUE TITLE
Add some information regarding the generated pdf, including its location, in the payload of the event

### ISSUE THREAD

**Issue by aaronfultonnz** [pdfplum/pdfplum#23]
I'm wondering if there is a way of being notified when the PDF has been created? I am using the firestore document to trigger the PDF generation. Apologies if I've missed this in the documentation. 

I need to send the generated PDF as an email attachment.

**Comment by sassanh** [comment]
PDFPlum triggers an event when it runs successfully (after generating the pdf and storing/serving it).
It also triggers an error event when it fails.

This is the relevant code for the firestore version: https://github.com/sassanh/pdf-plum/blob/ede0538/firestore-pdf-generator/functions/lib/produce_pdf.ts#L67

The success event for firestore version is `firebase.extensions.pdfplum.firestore-pdf-generator.v1.complete` and the failure event is `firebase.extensions.pdfplum.firestore-pdf-generator.v1.error`.

You should register an event listener function in Firebase to run when these events are triggered and send the email.

The event payload includes the timestamp of the moment the job was done, the publicUrl of the pdf (if it is set to make the pdf public) the size of the pdf file as well as all the parameters passed to it and all the parameters set via extension parameters.

Above information should be enough to extract the exact location of the generated file. But I think we need to add the exact location of the generated file to make things easier for developers. So lets keep this issue open.

**Comment by chenliyang1024** [comment]
Hi Sassanh, 

Can you provide some example of event? my function never get triggered/

![image](https://github.com/pdfplum/pdfplum/assets/16925951/e4732947-8195-422f-a8b9-ac1f8a9c9e11)

**Comment by sassanh** [comment]
@chenliyang1024 It's a good idea, but not very relevant to this issue, please create a separate issue for it so that we can track each separately.

**Comment by sassanh** [comment]
- https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.17.1-rc.2
- https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/http-pdf-generator@0.17.1-rc.2

**Comment by sassanh** [comment]
This is address in 17.0.1, it is published now.
