### ISSUE TITLE
value.toLowerCase is not a function in parse parameter for http generator

### ISSUE THREAD

**Issue by axelgroupe** [pdfplum/pdfplum#26]
### Description

Hi, i'm trying to use the http version of the plugin but i get a parsing error.

{"error":"value.toLowerCase is not a function","context":"parse parameters"}

Any reason the problem could be my body data structure ?

{
    "templatePath": "axelcontrol-98dd0.appspot.com/template/pdfTemplates.zip",
    "outputFileName": "nc.pdf",
    "chromiumPdfOptions": {
        "format": "a5",
        "printBackground": true
    },
    "adjustHeightToFit": "no",
    "data": {
        "openDate": "07/09/2023 14:20:52",
        "origin": "AX48xvZ6yssBUlN8YHAD",
        "detailOrigin": "colis cassé",
        "delta": "gfkfkffhkfk",
        "severityIndex": "5",
        "indicator": "label-danger",
        "thirdParty": "",
        "batchNumber": "gff",
        "quantityConcerned": "fjf",
        "otherStatus": "blocage",
        "images": [],
        "cause": "fkf",
        "immediateCorrection": null,
        "immediateCorrectionResponsible": "SenCanWrite - sebdebillere@hotmail.fr",
        "immediateCorrectionDueDate": "09/09/2023 14:20:52",
        "immediateCorrectionDoneDate": null,
        "correctiveAction": null,
        "correctiveActionResponsible": "undefined - undefined",
        "correctiveActionDueDate": null,
        "correctiveActionDoneDate": "12/01/2024 11:03:30",
        "efficiency": null,
        "checkDate": null,
        "docs": [
            {
                "privateUrl": "company/k8bXHomCs0YXtP0FtPVx/nonComformities/66c8b4d9-1f18-4d40-b2d7-dfe5b6c81ffa.pdf",
                "id": "66c8b4d9-1f18-4d40-b2d7-dfe5b6c81ffa",
                "sizeInBytes": 122479,
                "name": "devis_brouillon_56001.pdf",
                "publicUrl": "https://firebasestorage.googleapis.com/v0/b/axelcontrol-98dd0.appspot.com/o/company%2Fk8bXHomCs0YXtP0FtPVx%2FnonComformities%2F66c8b4d9-1f18-4d40-b2d7-dfe5b6c81ffa.pdf?alt=media&token=5a53dd05-2c33-4119-98e2-b0f4385f535f",
                "new": true
            }
        ]
    }
}

Thank you forward.

### Steps to reproduce the behavior

  const handleGeneratePdfFile = async () => {
    setGenerate(true);
    const idToken = await props.firebase.auth().currentUser.getIdToken(true);
    const url = 'https://corsproxy.io/?' + encodeURIComponent(`${BASE_URL}/ext-http-pdf-generator-executePdfGenerator`);
    // eslint-disable-next-line no-undef
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        authorization: `Bearer ${idToken}`,
      },
      body: JSON.stringify({
        templatePath: 'axelcontrol-98dd0.appspot.com/template/pdfTemplates.zip',
        outputFileName: 'nc.pdf',
        chromiumPdfOptions: {
          format: 'a5',
          printBackground: true,
        },
        adjustHeightToFit: 'no',
        data: {
          openDate: comformity?.openDate,
          origin: comformity?.origin,
          detailOrigin: comformity?.detailOrigin,
          delta: comformity?.delta,
          severityIndex: comformity?.severityIndex,
          indicator: getNonComformityPdfIndicator(comformity),
          thirdParty: getThirdpartyNameById(comformity.thirdParty, thirdParties),
          batchNumber: comformity?.batchNumber,
          quantityConcerned: comformity?.quantityConcerned,
          otherStatus: comformity?.otherStatus,
          images: comformity?.images || [],
          cause: comformity?.cause,
          immediateCorrection: comformity?.immediateCorrection,
          immediateCorrectionResponsible: getUserUsernameAndPasswordFromId(
            users, comformity?.immediateCorrectionResponsible),
          immediateCorrectionDueDate: comformity.immediateCorrectionDueDate,
          immediateCorrectionDoneDate: comformity?.immediateCorrectionDoneDate,
          correctiveAction: comformity?.correctiveAction,
          correctiveActionResponsible: getUserUsernameAndPasswordFromId(users,
            comformity?.correctiveActionResponsible),
          correctiveActionDueDate: comformity?.correctiveActionDueDate,
          correctiveActionDoneDate: comformity?.correctiveActionDoneDate,
          efficiency: comformity?.efficiency,
          checkDate: comformity?.checkDate,
          efficiencyComment: comformity?.efficiencyComment,
          docs: comformity?.docs,
        }
      }),
    });
    console.log(response, 'response');
  };

### Logs

Error TypeError: value.toLowerCase is not a function
    at /workspace/build/src/parse_parameters.js:48:36
    at Array.map (<anonymous>)
    at parseParameters (/workspace/build/src/parse_parameters.js:46:201)
    at runAction (/workspace/build/lib/utilities/action.js:43:20)
    at /workspace/build/src/index.js:60:51
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/providers/https.js:51:16)
    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by sassanh** [comment]
Please change `true` booleans to `"true"` strings.

**Comment by sbodrero** [comment]
Thank @sassanh did not get it first.

**Comment by sassanh** [comment]
I'm deploying a version accepting booleans soon. Will close after that.

**Comment by sassanh** [comment]
This issues should be resolved in 17.0.1, it is published now.
