### ISSUE TITLE
CORS when calling

### ISSUE THREAD

**Issue by chenliyang1024** [pdfplum/pdfplum#28]
### Description

![image](https://github.com/pdfplum/pdfplum/assets/16925951/c0358e15-fee2-4e70-a8fa-1eb7efce9ec3)

This cors issue happened from both domain and localhost

### Steps to reproduce the behavior

![image](https://github.com/pdfplum/pdfplum/assets/16925951/36e9c169-b80a-4576-8a87-216883fb1e92)

### Logs

-

**Comment by sassanh** [comment]
@chenliyang1024 
Isn't the CORS issue present when you open your template in a normal Chrome instance?

**Comment by sassanh** [comment]
Cross-Origin Resource Sharing issues should be handled in the server, I doubt if there is anything we can do about it in pdfplum. Let me know if you have any suggestions.
BTW, as long as the template renders without any issues in your local Chrome, it should work for pdfplum too. So you should be able to resolve CORS issues locally first before uploading the template.

**Comment by chenliyang1024** [comment]
I tried with many ways to avoid this, however, since the http request is called from browser, it will always caused CORS issue. I works fine with postman,and wget. but not browser. 
since I have no control of the this extension code, wondering how do it resolve CORS from server side?
All of my other fucntions are fine, i handle cors for all of them, but i cannot add code to extension code.

please advice.
