### ISSUE TITLE
PDF File unable to download once doc is captured

### ISSUE THREAD

**Issue by JacksonRossiDev** [pdfplum/pdfplum#30]
### Description

This FIrebase Extension is exactly what I am looking for! 

I downloaded the extension and created a simple template folder that contains an index.html file with this code: 

`<!DOCTYPE html>
<html>
<head>
    <title>Invoice</title>
</head>
<body>
    <h1>Invoice for {{customerName}}</h1>
    <p>Date: {{date}}</p>
    <table>
        <thead>
            <tr>
                <th>Item</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {{#each items}}
                <tr>
                    <td>{{this.name}}</td>
                    <td>{{this.price}}</td>
                </tr>
            {{/each}}
        </tbody>
    </table>
    <p>Total: {{total}}</p>
</body>
</html>`

I then created a new user in firebase, which triggered PDFPlum. Here is the code that is used to trigger the PDF generation: 

`export const doCreateUserWithEmailAndPassword = async (email, password) => {
  return createUserWithEmailAndPassword(auth, email, password)
  .then((result) => {
    setDoc(doc(db, "patients", auth.currentUser.uid),
    
    {
      "customerName": "John Doe",
      "date": "2021-12-01",
      "items": [
          {"name": "Item 1", "price": "$10.00"},
          {"name": "Item 2", "price": "$15.00"}
      ],
      "total": "$25.00",
      "_pdfplum_config": {
          "outputStorageBucket": "gs://a-custom-fit-in-motion.appspot.com",
          "outputFileName": "invoice.pdf",
          "adjustHeightToFit": true,
          "chromiumPdfOptions": {
              "format": "A4",
              "printBackground": true
          }
      }
  });
    })
    .catch((error) => {
        console.log(error)
 
});;
};`

After this, I realized that this worked! The invoice.pdf file was placed in the correct bucket!

The problem is that I am unable to view/open/download the file. It is simply sitting in my bucket and I have no idea how to test/use this file. Here is a screenshot of what this file looks like in my storage bucket (It appears there is no download url for the files that are created): 

![Screenshot 2024-03-22 at 12 29 23 PM](https://github.com/pdfplum/pdfplum/assets/81778560/33b8a1d6-2c25-4771-a107-671800fdad69)

### Steps to reproduce the behavior

Please follow the listed steps above

### Logs

![Screenshot 2024-03-23 at 12 04 31 PM](https://github.com/pdfplum/pdfplum/assets/81778560/27900169-229e-4028-8156-748e714d575d)

**Comment by sassanh** [comment]
I'm glad you found it useful :-)

I think this is happening because of this change in the Firebase Storage behavior: https://stackoverflow.com/questions/63468686/download-url-not-present-in-firebase-console#:~:text=Download%20URLs%20are%20not%2Fno,up%20in%20the%20Firebase%20console.

I will add an option to let the developer create download link as suggested in that thread.

If you just want to check the output pdfs to see how it's working, a temporary workaround is to set SHOULD_MAKE_PDF_PUBLIC extension parameter. To do so you need to reconfigure the extension by clicking on this button:
<img width="415" alt="image" src="https://github.com/pdfplum/pdfplum/assets/1270688/66b5a3e4-8b23-439e-b788-92e9fa9ee933">

and change the value of this parameter to "Public":
<img width="549" alt="image" src="https://github.com/pdfplum/pdfplum/assets/1270688/66f7e672-9db8-4bff-b8b3-7ba03e150290">

Then if you pass `"returnPdfInResponse": false` in the JSON parameters of the HTTP request, it will return a JSON which contains a `publicUrl` key, the value of this field is a url and you should be able to open it in your browser.

**Comment by JacksonRossiDev** [comment]
Thank you so much for adding this option! 

I followed your instructions as follows: 

Changed output storage bucket to public:
![Screenshot 2024-03-24 at 9 53 02 AM](https://github.com/pdfplum/pdfplum/assets/81778560/97fba817-2223-4663-9c29-0d8b449b0002)

I then added the returnPdfInResponse and set it to false in the request: 

![Screenshot 2024-03-24 at 9 49 48 AM](https://github.com/pdfplum/pdfplum/assets/81778560/058f0554-ee60-4064-a07f-c78c3f499a75)

I then added the new file and checked my storage bucket. It looks like the PDF was generated correctly! The only problem is that there still is no link/generated URL to be able to view the PDF. Can you please let me know if this was done correctly? Thank you so much!
![Screenshot 2024-03-24 at 9 53 45 AM](https://github.com/pdfplum/pdfplum/assets/81778560/570e8d5c-9668-4b6c-97b8-0f7c290ebb45)

**Comment by sassanh** [comment]
You also need this part:

> it will return a JSON which contains a `publicUrl` key, the value of this field is a url and you should be able to open it in your browser.

This workaround doesn't make the link in the storage bucket, it provides a public link in the http response.

**Comment by JacksonRossiDev** [comment]
Ok, great. Where can I find this http response?

**Comment by JacksonRossiDev** [comment]
I am sorry, I  don't have much experience calling endpoints in react. How would I call this with my parameters via react? Thank you so much for helping

**Comment by sassanh** [comment]
No worries, it depends on which library you are using to call endpoints. Are you using `fetch` or a library? It would be helpful if you share the piece of code responsible for sending the request.

**Comment by JacksonRossiDev** [comment]
I am using firebase to read/write data to/from the db. 

For example: 

`function writeUserData(userId, name, email, imageUrl) {
  const db = getDatabase();
  set(ref(db, 'users/' + userId), {
    username: name,
    email: email,
    profile_picture : imageUrl
  });
}`

**Comment by sassanh** [comment]
I see, so you are not using the http version, you are using the firestore version, this workaround works only for the http version.
Please wait a few days until I release the new version.

**Comment by JacksonRossiDev** [comment]
Awesome. You are so helpful! Thank you so much my friend

**Comment by JacksonRossiDev** [comment]
Hi @sassanh - Quick question

I am going through the PDFs that were captured and am realizing that only the first page of the index.html file is being captured. Can you please take a look into this when you have a chance. Thanks so much my friend.

**Comment by JacksonRossiDev** [comment]
![Screenshot 2024-04-17 at 7 33 34 PM](https://github.com/pdfplum/pdfplum/assets/81778560/28288852-aaf8-43c5-bbfd-9058e32c47f2)

Parameters are set in firebase document request here:
![Screenshot 2024-04-17 at 7 35 27 PM](https://github.com/pdfplum/pdfplum/assets/81778560/c6788447-2998-4a73-a0eb-c7153878c8da)

**Comment by sassanh** [comment]
@JacksonRossiDev It is happening because `adjustHeightToFit` is set.
It is mentioned in the [docs](https://github.com/pdfplum/pdfplum/blob/main/http-pdf-generator/PARAMETERS.md#adjust_height_to_fit-required).

**Comment by sassanh** [comment]
@JacksonRossiDev Let me know if it is not fixed by setting `adjustHeightToFit`.
