### ISSUE TITLE
unable to call http in Flutter/Dart. 'Only Json request supported' error

### ISSUE THREAD

**Issue by vtvtvtvtvtvt** [pdfplum/pdfplum#37]
### Description

I converted it to flutter API call. I tried with packages like Dio and HTTP but I get the same error. I also tried calling the PowerShell command equivalent of 'wget', which works perfectly.  I am unable to see the logs in google cloud as how the json is sent but is does not have any data, just the Error: Only JSON requests are supported. 

### Steps to reproduce the behavior

below is the custom code in flutterflow
// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/sqlite/sqlite_manager.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/actions/index.dart'; // Imports other custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom action code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import 'package:dio/dio.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

// Custom Action Function

Future<String> callPdfGeneratorAPI(
  String templatePath,
  String? outputFileName,
  bool? returnPdfInResponse,
  String? format,
  bool? printBackground,
  bool? adjustHeightToFit,
  String? companyName,
  String? companyImage,
  String? date,
  String? invoiceId,
  String? soldbyContactName,
  String? soldbyCompany,
  String? soldbyAddress,
  String? soldbyphoneNumber,
  String? soldbyEmail,
  String? soldbygstn,
  String? billContactName,
  String? billClientCompany,
  String? billAddress,
  String? billphoneNumber,
  String? billtogstn,
  String? shipNameOrDept,
  String? shipClientCompany,
  String? shipAddress,
  String? shipphoneNumber,
  double? subtotal,
  int? discount,
  double? taxRate,
) async {
  var headers = {'Content-Type': 'application/json'};

  var data = {
    "templatePath": templatePath,
    "outputFileName": outputFileName,
    "returnPdfInResponse": returnPdfInResponse,
    "chromiumPdfOptions": {
      "format": format,
      "printBackground": printBackground
    },
    "adjustHeightToFit": adjustHeightToFit,
    "data": {
      "companyName": companyName,
      "companyImage": companyImage,
      "date": date,
      "invoiceId": invoiceId,
      "soldbyContactName": soldbyContactName,
      "soldbyCompany": soldbyCompany,
      "soldbyAddress": soldbyAddress,
      "soldbyphoneNumber": soldbyphoneNumber,
      "soldbyEmail": soldbyEmail,
      "soldbygstn": soldbygstn,
      "billContactName": billContactName,
      "billClientCompany": billClientCompany,
      "billAddress": billAddress,
      "billphoneNumber": billphoneNumber,
      "billtogstn": billtogstn,
      "shipNameOrDept": shipNameOrDept,
      "shipClientCompany": shipClientCompany,
      "shipAddress": shipAddress,
      "shipphoneNumber": shipphoneNumber,
      "subtotal": subtotal,
      "discount": discount,
      "taxRate": taxRate
    }
  };
  var dio = Dio();
  var response = await dio.request(
    'https://asia-south1-oopkaran.cloudfunctions.net/ext-http-pdf-generator-executePdfGenerator',
    options: Options(
      method: 'POST',
      headers: headers,
    ),
    data: data,
  );

  if (response.statusCode == 200) {
    // Success
    return 'PDF generated successfully';
  } else {
    // Handle other status codes
    return 'Request failed with status: ${response.statusMessage}.';
  }
}

// Set your action name, define your arguments and return parameter,
// and then add the boilerplate code using the green button on the right! 

### Logs

{
  "textPayload": "Function execution started",
  "insertId": "1ohtv1kfxb78uo",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "********",
      "region": "asia-south1",
      "function_name": "ext-http-pdf-generator-executePdfGenerator"
    }
  },
  "timestamp": "2024-07-07T15:08:16.432662905Z",
  "severity": "DEBUG",
  "labels": {
    "execution_id": "lojcc1rg8ma0",
    "runtime_version": "nodejs18_20240630_18_20_3_RC00"
  },
  "logName": "projects/****/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/******/traces/516fd89b115d6bf02ea0a74a2648e755",
  "receiveTimestamp": "2024-07-07T15:08:16.679470743Z"
}

{
  **"textPayload": "Error: Only JSON requests are supported.\n**    at /workspace/build/src/index.js:51:22\n    at cloudFunction (/workspace/node_modules/firebase-functions/lib/v1/providers/https.js:51:16)\n    at /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/function_wrappers.js:98:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)",
  "insertId": "668aaf600006a8ed15645c9a",
  "resource": {
    "type": "cloud_function",
    "labels": {
      "project_id": "******",
      "region": "asia-south1",
      "function_name": "ext-http-pdf-generator-executePdfGenerator"
    }
  },
  "timestamp": "2024-07-07T15:08:16.436461Z",
  "severity": "ERROR",
  "labels": {
    "execution_id": "lojcc1rg8ma0",
    "runtime_version": "nodejs18_20240630_18_20_3_RC00",
    "instance_id": "0087244a8061becf0e8ef5c10cced35562ead00fb5a17e16c217a2ccb823752bc954b934ae22f26ed173f892e150abfc786e6eda21eeb1699394f7e6da3270a55a90"
  },
  "logName": "projects/****/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
  "trace": "projects/****/traces/516fd89b115d6bf02ea0a74a2648e755",
  "receiveTimestamp": "2024-07-07T15:08:16.679470743Z",
  "errorGroups": [
    {
      "id": "CIKVvazkw8SWYQ"
    }
  ]
}

**Comment by sassanh** [comment]
This library has no control over how the client, whether it's Flutter or something else, calls it. It expects a certain type of input and will generate a certain type of output based on that.

I hope you can quickly find out the issue with the requests generated in your client, but unfortunately I have to close it without being able to help you.
