### ISSUE TITLE
Issues with Template Not Picking Up the Data 

### ISSUE THREAD

**Issue by atakoraworks** [pdfplum/pdfplum#40]
### Description

This is the solution we have been searching for but I have Two MAJOR issues with this. 

- First for some reasons even though
[pdfGen.zip](https://github.com/user-attachments/files/16939560/pdfGen.zip)
 my template looks fine and renders just fine in my browser (chrome) and from my IDE, when uploaded to firebase and called via the http extension , it generates an empty PDF doc. Attached is my template zipped.
I added some logging steps into my script.js file and from the GCP Logs View i can see the log 
`QR code element not found for order number 370251045100182`, this means that it is not picking up the value from the template as you will see from my template.
- Second i am struggling with how to pass the data from the payload from the wget called over to my script.js. I don;t know how to make that happen or at least the example templates i have looked that do not really explain how that is happening.
As of now i had the data hard coded in my index.html file for testing purpose

### Steps to reproduce the behavior

- Firebase project
- Installed http pdfplum extension and configure it as describved in the doc.
- Upload the template and execute

### Logs

{
  "insertId": "66dfc9f8000d1186190fba40",
  "jsonPayload": {
    "args": [
      {}
    ],
    "stackTrace": [
      {
        "lineNumber": 27,
        "columnNumber": 28,
        "url": "http://localhost:3000/scripts.js"
      },
      {
        "columnNumber": 24,
        "url": "http://localhost:3000/scripts.js",
        "lineNumber": 16
      },
      {
        "url": "http://localhost:3000/scripts.js",
        "lineNumber": 89,
        "columnNumber": 0
      }
    ],
    "location": "[Circular]",
    "message": "Message logged while loading template bundle in the browser",
    "type": "error",
    "text": "QR code element not found for order number 370251045100182"
  },
}

**Comment by sassanh** [comment]
I'm glad you found it useful!

I noticed you have a big part of your html inside a `<script>` tag, that explains why it renders an empty page. I'm talking about lines 14 to 69 of the index.html.
It is also probably the reason `document.querySelector` fails to find the qr code element.

**Comment by atakoraworks** [comment]
Thank you for the prompt response. I figured it out. You are right the `<script>` tag was definitely the issue.
I also figured out how the payload is injected in there. All good.
