### ISSUE TITLE
Cant Install extension into firebase

### ISSUE THREAD

**Issue by anywheresa** [pdfplum/pdfplum#5]
Hi
This extension is not installing into Firebase. 

The error reads..... "An error occurred while fetching this extension.

I have zipped the html template and uploaded it to starage.
This is my storage rules....

rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if false;
    }
  }
}

**Comment by sassanh** [comment]
Sorry, it is not published yet, we are going to publish it in a few hours, I will inform you here.

**Comment by sassanh** [comment]
Hey @anywheresa,
PDFPlum is published now, I hope it works seamlessly for you, let's keep this issue open for a while in case you encounter any issues.

**Comment by anywheresa** [comment]
Thank you. I appreciate it. I will revert back to you in the next day or two.

**Comment by sassanh** [comment]
Did you try reinstalling the extension? I have seen this issue recently several times and I noticed reinstalling the extension by clicking on the reinstall button in the red error box.

**Comment by anywheresa** [comment]
Yes, I re-installed but had to do so with specifying a collection id for a trigger. I used your demo but pdf is not stored in storage bucket when doing a wget. It is exported to local drive but corrupt.

**Comment by sassanh** [comment]
> Yes, I re-installed but had to do so with specifying a collection id for a trigger.

In my experience clicking on the retry button is enough to install the extension without any errors, it would be great if you could double check it and let me know if it works without setting `FIRESTORE_COLLECTION`.

> I used your demo but pdf is not stored in storage bucket when doing a wget.

Did you already set `OUTPUT_STORAGE_BUCKET`? If yes, please share the logs here so that I can investigate it.

> It is exported to local drive but corrupt.

Please share the corrupt PDF file with me.

**Comment by anywheresa** [comment]
My apologies but I have had to bail on your solution as I do not have time for troubleshooting due tomy project  being over deadline already. I had to implement JSPDF instead, which I used in another project before.

I would however like to thank you for your responsiveness and willing to assist.
Kind Regards
Deon

**Comment by sassanh** [comment]
I'm sorry pdfplum didn't work for you. I will try to find a way to reproduce this issue on my side and resolve it. I hope you consider pdfplum as the pdf generator in your future projects.

**Comment by anywheresa** [comment]
No problem. I certainly will. Thank you for your hard work and effort building this extension.

**Comment by sassanh** [comment]
Reproduction screencast: https://user-images.githubusercontent.com/1270688/220292309-3f5dad5e-61dc-4c99-858c-73b63c1b72c3.mov

As shown in this screencast, installing the extension for the first time shows an error about cloud functions (it shows only on new projects, installing the extension again in the same project won't show this error in my experience) clicking on the retry button of the error message will try to reinstall the extension and this time it shows an error about an invalid url composed with `FIRESTORE_COLLECTION` as mentioned [here](https://github.com/pdfplum/pdfplum/issues/5#issuecomment-1429777678):

> ; RESOURCE_ERROR at /deployments/firebase-ext-pdfplum/resources/executePdfGeneratorFirestore: {"ResourceType":"gcp-types/cloudfunctions-v1:projects.locations.functions","ResourceErrorCode":"400","ResourceErrorMessage":"Failed to configure trigger for event-type:providers/cloud.firestore/eventTypes/document.create resource:projects/bladdermatters-c3375/databases/(default)/documents/${param:FIRESTORE_COLLECTION}/{id} service:firestore.googleapis.com. The Event trigger resource 'projects/bladdermatters-c3375/databases/(default)/documents/${param:FIRESTORE_COLLECTION}/{id}' is invalid."}**_

Clicking on the retry button again will successfully install the extension.

Successive installations/updates of the extension on the same project will only show the second error and a single retry attempt will be enough.

I will report this to Firebase team.

**Comment by runelk** [comment]
@sassanh I came across this issue a while back as well. I didn't specify the firestore collection and got an error (see the  attached screenshot). I didn't try to reinstall, but I tried on a different Firebase instance a few days later, making sure that the collection was specified, and got no errors. Could there be some kind of missing value check for that particular field in the extension configuration?


![Screenshot-pdfplum-extension](https://user-images.githubusercontent.com/303580/220705995-a303df67-2b5a-4bc8-b285-5f59d284d384.jpg)

**Comment by sassanh** [comment]
I have reported this to Firebase team, I think this is an issue in Firebase extension installation process.
This extension has 2 ways to be triggered, one being an http call, the other being a Firestore document creation event. Some users may only need the first one and don't want to setup Firestore on their project, so we need to keep `FIRESTORE_COLLECTION` an optional field. This approach is suggested by Firebase team. It was working until few weeks ago, but suddenly extension installation started failing with this error, fortunately just pressing the retry button is enough to have a successful installation (you don't need to setup Firestore nor setting a value for `FIRESTORE_COLLECTION`)
As far as I know Firebase extensions team are working on better solutions for situations like this to make some events optional (here we want the Firestore creation even to be optional). Meanwhile if we see it is causing trouble for users we can consider separating the extension into two extensions, one being triggered with http calls, the other being triggered by Firestore creation events.

**Comment by sassanh** [comment]
There is no way to have an optional API service in an extension now, which means if our extension needs Firestore in some scenarios, it won't work unless you setup Firestore on your project even if you don't need the functionality relying on Firestore.

That being said I decided to split the extension into two extensions: http-pdf-generator and firestore-pdf-generator. It should resolve the issue reported here and simplify the installation process as well.

The installation links for these two extensions are in the homepage of this repository, I will update the website soon too.

Let's keep this issue open for a few days to complete tests and see if it is actually resolved.

**Comment by sassanh** [comment]
I finished my tests. There were some issues and I fixed them. Now it seems to be working alright.
