### ISSUE TITLE
Missing roles required(?) by the extension

### ISSUE THREAD

**Issue by cabljac** [pdfplum/pdfplum#6]
Hi, how is it that there are no roles required by the extension in the extension.yaml? Does it not require any?

**Comment by sassanh** [comment]
Currently it doesn’t require any. I will try to set up roles for accessing Firebase storage so that one doesn’t need to make their storage public.

**Comment by sassanh** [comment]
I added `storage.admin` role, feel free to reopen if your concern is not addressed yet.
Relevant commit: https://github.com/pdfplum/pdfplum/commit/ed70637c52e8645df6916f4e09479d2a94feac76
