### ISSUE TITLE
Typo in wget command code?

### ISSUE THREAD

**Issue by fyimail** [pdfplum/pdfplum#7]
In the POSTINSTALL.md doc (https://github.com/pdfplum/pdfplum/blob/a313de96e01f3b2f125fcc93441287404f83a5ca/http-pdf-generator/POSTINSTALL.md) you have the following code:

 wget "https://${param:LOCATION}-${PROJECT_ID}.cloudfunctions.net/ext-${EXT_INSTANCE_ID}-executePdfGeneratortemplatePath=${STORAGE_BUCKET}/demo.zip&outputFileName=demo.pdf&chromiumPdfOptions[format]=a5&chromiumPdfOptions[printBackground]=true&adjustHeightToFit=no&data[text]=Lorem ipsum dolor sit amet consectetur adipisicing elit.&data[flag]=OK&data[articles][0][title]=ABCD&data[articles][0][content]=Abcd content&data[articles][1][title]=EFGH&data[articles][1][content]=Efgh content&data[articles][2][title]=IJKL&data[articles][2][content]=Ijkl content&data[articles][3][title]=MNOP&data[articles][3][content]=Mnop content&data[articles][4][title]=QRST&data[articles][4][content]=Qrst content&data[colors][warm][0]=Red&data[colors][warm][1]=Yellow&data[colors][warm][2]=Orange&data[colors][cold][0]=Green&data[colors][cold][1]=Blue&data[colors][cold][2]=Gray&data[info][Age]=38&data[info][Name]=John Doe&data[info][Birthday]=1985%2F20%2F06&data[info][Address]=Silicon Valley" -O demo.pdf

It's not working and could it be because it is missing a question mark between "executePdfGenerator" and "templatePath"?

**Comment by sassanh** [comment]
Yes, a question mark is needed there. I will fix this typo.

**Comment by fyimail** [comment]
> Yes, a question mark is needed there. I will fix this typo.

Awesome, thanks!
