### ISSUE TITLE
'Build failed' error after installing extension via Firebase Console

### ISSUE THREAD

**Issue by fyimail** [pdfplum/pdfplum#8]
After clicking the Install button, the Generate PDFs via HTTP seems to install fine (no errors on Extensions screen) but when I got to the Functions screen there is a red exclamation point icon appears indicating "Function deployment failed" and when I look at the log I see this snippet:

  "protoPayload": {
    "@type": "type.googleapis.com/google.cloud.audit.AuditLog",
    "status": {
      "code": 3,
      "message": "Build failed: build/http-pdf-generator/functions/src/index.js does not exist; Error ID: f105e7fd"
    },

The default values for "Template path" and "Output Firebase Storage bucket name" appear to be correct.

Could you advise on how to resolve this error?

**Comment by sassanh** [comment]
Thanks for reporting this! I can reproduce this issue on my side, I will get back to you soon.

**Comment by sassanh** [comment]
@fyimail The issue should be resolved in this release candidate: https://console.firebase.google.com/u/0/project/_/extensions/install?ref=pdfplum%2Fhttp-pdf-generator@0.12.18-rc.3
Please note that this 0.12.18 rc is ony accessible via the link I provided above, installing from extensions.dev will install the old 0.12.16 version.

**Comment by fyimail** [comment]
@sassanh Thanks for the speedy response & fix! It's working nicely 🤩 Could you also send me an rc link for the firestore-pdf-generator as there was a similar functions deployment error for that too?

**Comment by sassanh** [comment]
You can use this link:
https://console.firebase.google.com/project/_/extensions/install?ref=pdfplum/firestore-pdf-generator@0.12.18-rc.3
